name: GitHub Metrics
on:
  # Schedule to run every 2 hours
  schedule: [{cron: "0 */2 * * *"}]
  # Allow manual triggering
  workflow_dispatch:
  # Trigger on push to main branch but ignore commits from the metrics bot
  push:
    branches: [ main ]
    paths-ignore:
      - 'github-metrics.svg'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          # Basic settings
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          committer_branch: main
          committer_message: "Update metrics [Skip GitHub Action]"
          committer_gname: GitHub Action
          committer_gemail: action@github.com
          output_action: commit
          skip_commit: ${{ startsWith(github.event.head_commit.message, 'Update metrics') }}
          
          # Enable base settings for metrics display
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          
          # Commit statistics with more detailed info
          plugin_lines: yes
          plugin_lines_sections: repositories, history
          plugin_lines_repositories_limit: 10
          plugin_lines_history_limit: 1000
          
          # More accurate commit history
          plugin_contributors: yes
          plugin_contributors_sections: repositories, organizations
          plugin_contributors_contributions: yes
          
          # Remove the isocalendar and replace with more detailed stats
          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          
          # Add contributions section showing lifetime contributions
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_repositories: yes

