name: GitHub Metrics
on:
  # Schedule to run every 2 hours
  schedule: [{cron: "0 */2 * * *"}]
  # Allow manual triggering
  workflow_dispatch:
  # Trigger on push to main branch but ignore commits from the metrics bot
  push:
    branches: [ main ]
    paths-ignore:
      - 'github-metrics.svg'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          # Basic settings
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          committer_branch: main
          committer_message: "Update metrics [Skip GitHub Action] - Runner: ${{ runner.os }}"
          committer_gname: GitHub Action
          committer_gemail: action@github.com
          output_action: commit
          skip_commit: ${{ startsWith(github.event.head_commit.message, 'Update metrics') }}
          
          # Enable base settings for metrics display - focused on commits
          base: header, activity, repositories, metadata
          base_indepth: yes
          
          # Activity plugin with commits focus - all time
          plugin_activity: yes
          plugin_activity_limit: ${{ vars.METRICS_ACTIVITY_LIMIT || 100 }}
          plugin_activity_days: ${{ vars.METRICS_ACTIVITY_DAYS || 365 }}
          plugin_activity_filter: commits
          plugin_activity_visibility: all
          plugin_activity_timestamps: yes
          plugin_activity_colors: yes
          
          # Include workflow run information
          plugin_traffic: yes
          
          # Include GitHub environment info
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_url: https://github.com/${{ github.repository }}
          
          # Customized colors for better visual appeal
          config_order: base.header, activity, base.repositories
          config_padding: 10%
          config_animations: yes
          config_display: columns
          config_timezone: Europe/London
          
          # Color customization
          extras_css: |
            :root {
              --color-calendar-graph-day-bg: #ebedf0;
              --color-calendar-graph-day-border: rgba(27,31,35,0.06);
              --color-calendar-graph-day-L1-bg: #39d353;
              --color-calendar-graph-day-L2-bg: #26a641;
              --color-calendar-graph-day-L3-bg: #006d32;
              --color-calendar-graph-day-L4-bg: #0e4429;
              --color-text-primary: #24292f;
              --color-text-secondary: #57606a;
              --color-bg-canvas: #ffffff;
              --color-bg-canvas-inset: #f6f8fa;
              --color-bg-primary: #ffffff;
            }
            .activity {
              animation: rainbow 10s ease-in-out infinite;
            }
            @keyframes rainbow {
              0%, 100% { color: #7F00FF; }
              14% { color: #0000FF; }
              28% { color: #00FFFF; }
              42% { color: #00FF00; }
              57% { color: #FFFF00; }
              71% { color: #FF7F00; }
              85% { color: #FF0000; }
            }
